#Connexion à la base de données
 spring.datasource.url=jdbc:sqlserver://localhost;databasename=ENI_BIBLIOTHEQUE;integratedSecurity=false;encrypt=false;trustServerCertificate=false
 spring.datasource.username=sa 
 spring.datasource.password=Naoures@91
 
 #Détail des requêtes pour le développement 
 spring.jpa.show-sql=true
 spring.jpa.hibernate.ddl-auto=update
 
#Détail des requêtes pour le développement
# Logs Hibernate (si utilisé)
logging.level.org.hibernate.SQL=DEBUG

# Voir les paramètres SQL
#logging.level.org.hibernate.type.descriptor.sql=TRACE

#JWT
app.jwt.secret=4c7277213c687b3130423d4a4d6948532925233c664e5666636b714920527071
