
#Connexion à la base de données
 spring.datasource.url=jdbc:sqlserver://localhost;databasename=ENI_BIBLIO;integratedSecurity=false;encrypt=false;trustServerCertificate=false
 spring.datasource.username=sa 
 spring.datasource.password=Pa$$w0rd
 
 #Détail des requêtes pour le développement 
 spring.jpa.show-sql=true
 spring.jpa.hibernate.ddl-auto=update
 
#Détail des requêtes pour le développement
# Logs Hibernate (si utilisé)
logging.level.org.hibernate.SQL=DEBUG

# Voir les paramètres SQL
#logging.level.org.hibernate.type.descriptor.sql=TRACE

#JWT
app.jwt.secret=4c7277213c687b3130423d4a4d6948532925233c664e5666636b714920527071
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

curl.upload=curl --location 'http://localhost:8080/api/books' --request POST --form 'file=@C:/Users/HP/Downloads/image (7).png' --form 'book="{\"author\": \"Robert Martin\",\"available\": true,\"availableCopies\": 7,\"avgRating\": 4.8,\"category\": \"FANTASTIQUE\",\"description\": \"Clean coding\",\"id\": 2,\"isbn\": \"9780132352822\",\"title\": \"Clean Code\",\"totalCopies\": 10 }";type=application/json'

